export type CompanionPresentationSurface = "voice" | "setup";

/** Presentation-only CSS for the two small generated Companion surfaces. */
export function companionPresentationStyle(surface: CompanionPresentationSurface): string {
  return surface === "voice" ? voicePresentationStyle : setupPresentationStyle;
}

const voicePresentationStyle = `<style>
.visually-hidden{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
.voice-surface{position:relative;display:grid;grid-template-columns:112px minmax(0,1fr) 112px;align-items:stretch;width:100%;height:100%;overflow:hidden;border:1px solid #2a3b3d;border-radius:14px;background:#0b1011;color:#f3f0e8;isolation:isolate}
.voice-presence{position:relative;display:grid;place-items:center;min-width:0;overflow:hidden;border-right:1px solid #213033;background:#0e1719}
.voice-presence::before{position:absolute;top:15px;bottom:15px;left:17px;width:2px;background:#43d6d3;content:"";opacity:.72}.voice-presence::after{position:absolute;top:15px;right:14px;bottom:15px;width:1px;background:#24383a;content:""}
.voice-field{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;opacity:.86}.voice-field[hidden]{display:none}.voice-fallback{position:absolute;inset:0;width:100%;height:100%;padding:18px 13px 18px 25px;pointer-events:none;opacity:0;transition:opacity 140ms ease}.voice-presence[data-visual-fallback="visible"] .voice-fallback{opacity:.92}.voice-fallback path{fill:none;stroke:#43d6d3;stroke-linecap:round;stroke-linejoin:round;stroke-width:7}.voice-fallback .fallback-echo{stroke:#e8eee6;stroke-width:3;opacity:.42}
.voice-copy{display:flex;min-width:0;min-height:0;flex-direction:column;justify-content:center;padding:12px 14px 11px 17px;border-right:1px solid #213033;user-select:text;-webkit-user-select:text;-webkit-app-region:no-drag}.voice-copy p{margin:0;min-width:0}.voice-copy #state{overflow:hidden;color:#f3f0e8;font:650 14px/19px var(--ui);letter-spacing:-.16px;text-overflow:ellipsis;white-space:nowrap}.voice-copy #detail{display:-webkit-box;max-height:32px;overflow:hidden;color:#9eacab;font:430 12px/16px var(--ui);overflow-wrap:anywhere;-webkit-box-orient:vertical;-webkit-line-clamp:2}.voice-context{display:flex;align-items:center;gap:7px;margin-top:5px!important;overflow:hidden;color:#6f8989;font:9px/12px var(--mono);white-space:nowrap;text-overflow:ellipsis}.voice-context[hidden]{display:none}.voice-context #context{overflow:hidden;text-overflow:ellipsis}.context-mark{flex:0 0 auto;width:5px;height:5px;border:1px solid #43d6d3;transform:rotate(45deg)}
.voice-hint{display:flex;min-width:0;flex-direction:column;justify-content:center;align-items:flex-start;gap:5px;padding:0 14px;color:#f3f0e8;text-align:left}.voice-hint span{max-width:96px;color:#d7ddd5;font:600 11px/14px var(--ui)}.voice-hint kbd{padding:0;color:#6f8989;font:9px/12px var(--mono);letter-spacing:-.15px;white-space:nowrap}.voice-hint::before{width:18px;height:2px;background:#43d6d3;content:"";opacity:.72}.voice-action{appearance:none;border:0;background:transparent;cursor:pointer}.voice-action:hover span{color:#fff}.voice-action:focus-visible{outline:2px solid #43d6d3;outline-offset:-4px}
body[data-presentation-state="listening"] .voice-fallback path,body[data-presentation-state="transcribing"] .voice-fallback path,body[data-presentation-state="working"] .voice-fallback path,body[data-presentation-state="speaking"] .voice-fallback path{animation:signal-draw 760ms cubic-bezier(.2,.8,.2,1) 1 both}body[data-presentation-state="listening"] .voice-presence::before{background:#43d6d3}body[data-presentation-state="working"] .voice-presence::before{background:#818fdb}body[data-presentation-state="speaking"] .voice-presence::before{background:#8bc681}body[data-presentation-state="attention"] .voice-presence::before{background:#ff9e45}body[data-presentation-state="error"] .voice-presence::before{background:#d1514a}body[data-presentation-state="error"] .voice-copy #state{color:#f0b1aa}body[data-presentation-state="attention"] .voice-copy #state{color:#ffc18b}
@keyframes signal-draw{from{transform:translateX(-5px);opacity:.35}to{transform:translateX(0);opacity:.92}}body[data-state="review"] .voice-copy #detail,body[data-state="attention"] .voice-copy #detail{display:block;max-height:calc(100vh - 40px);overflow-y:auto;padding-right:5px;-webkit-line-clamp:unset;overscroll-behavior:contain;scrollbar-color:#385456 transparent}
@media (max-width:440px){.voice-surface{grid-template-columns:88px minmax(0,1fr) 92px}.voice-fallback{padding-left:20px;padding-right:8px}.voice-copy{padding-left:11px;padding-right:10px}.voice-hint{padding-left:10px;padding-right:10px}.voice-hint span{max-width:78px}}@media (prefers-reduced-motion:reduce){body[data-presentation-state] .voice-fallback path{animation:none!important}}
</style>`;

const setupPresentationStyle = `<style>
.setup-surface{position:relative;width:100%;height:100%;min-height:0;display:flex;flex-direction:column;padding:24px 26px 17px;border:1px solid #293a3b;border-radius:16px;background:#0d1213;color:#f3f0e8}.setup-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding-bottom:17px;border-bottom:1px solid #233133}.product-label{margin:0;color:#43d6d3;font:650 10px/14px var(--mono);letter-spacing:1.15px}.setup-header h1{margin:4px 0 0;color:#f3f0e8;font:650 22px/28px var(--ui);letter-spacing:-.45px}.window-controls{display:flex;align-items:center}.window-button,.link-button,.tray-button{appearance:none;border:0;background:transparent;cursor:pointer}.window-button{width:28px;height:28px;border-radius:6px;color:#82908f;font:18px/18px var(--ui)}.window-button:hover{background:#192426;color:#f3f0e8}
.connection-line{display:flex;align-items:center;gap:10px;min-height:45px;margin:16px 0 0;padding:0 13px;border:1px solid #25393b;border-radius:9px;background:#111a1b;color:#879695;font:12px/16px var(--ui);overflow:hidden}.connection-state{position:relative;flex:0 0 auto;padding-left:14px;color:#f1b16b;font:650 10px/16px var(--mono);letter-spacing:.35px}.connection-state::before{position:absolute;left:0;top:5px;width:7px;height:7px;border-radius:50%;background:#d99552;content:""}.connection-state[data-connected="true"]{color:#8ed2c0}.connection-state[data-connected="true"]::before{background:#43d6d3}#connection-host{min-width:0;overflow:hidden;color:#cad3ce;text-overflow:ellipsis;white-space:nowrap;font:12px/16px var(--ui)}.setup-intro{margin:11px 0 18px;color:#91a09e;font:12px/17px var(--ui)}
.defaults-panel,.pairing-panel{padding:15px 0 0;border-top:1px solid #233133}.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:12px;margin-bottom:11px}.section-heading p,.empty-kicker{margin:0;color:#dce5de;font:650 11px/15px var(--mono);letter-spacing:.5px}.section-heading span{color:#6d8381;font:10px/14px var(--ui)}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px 12px}.field{display:grid;gap:6px;color:#bfcac3;font:550 11px/15px var(--ui)}.field span{color:#9facaa}.field select,.field input{width:100%;min-width:0;height:37px;padding:0 10px;border:1px solid #2d4648;border-radius:7px;background:#0a1011;color:#f3f0e8;font:12px var(--ui);outline:0}.field select:hover,.field input:hover{border-color:#416365}.field select:focus,.field input:focus{border-color:#43d6d3;background:#0d1516}.field select:disabled{color:#6b7b79}.field input::placeholder{color:#5b6b69}.field input[aria-invalid="true"]{border-color:#d07468}#effort-field{grid-column:1/-1}.selection-summary{min-height:17px;margin:11px 0 0;color:#8b9b98;font:11px/16px var(--ui)}.defaults-actions{display:flex;align-items:center;gap:9px;margin-top:14px}.primary-button,.secondary-button{height:34px;border-radius:7px;cursor:pointer;font:650 12px var(--ui)}.primary-button{padding:0 14px;border:1px solid #43d6d3;background:#43d6d3;color:#081011}.primary-button:hover:not(:disabled){background:#66e1dd;border-color:#66e1dd}.primary-button:disabled{cursor:wait;opacity:.45}.secondary-button{padding:0 12px;border:1px solid #345153;background:#162324;color:#dce5de}.secondary-button:hover{border-color:#4d7475;background:#1a2c2e}.link-button,.tray-button{color:#8ca09d;font:11px var(--ui)}.link-button{margin-left:auto;padding:7px 0}.link-button:hover,.tray-button:hover{color:#f3f0e8}
.empty-provider{margin:auto 0;padding:18px 0;border-top:1px solid #233133;border-bottom:1px solid #233133}.empty-provider h2{margin:6px 0;color:#f3f0e8;font:650 17px/22px var(--ui);letter-spacing:-.2px}.empty-provider p:not(.empty-kicker){max-width:420px;margin:0 0 14px;color:#91a09e;font:12px/17px var(--ui)}.pairing-panel{padding-top:15px}.pairing-panel form{display:grid;gap:9px}.helper{margin:0;color:#708481;font:11px/15px var(--ui)}.helper code{color:#c3cfca;font:11px var(--mono)}.pairing-panel .primary-button{justify-self:start}.setup-message{min-height:38px;margin:14px 0 0;padding:9px 0 0 11px;border-left:2px solid #2f4d4e;color:#93a29f;font:11px/15px var(--ui);overflow-wrap:anywhere}.setup-message[data-kind="progress"]{border-color:#43d6d3;color:#b8dcd6}.setup-message[data-kind="success"]{border-color:#78bd9e;color:#acd8c1}.setup-message[data-kind="error"]{border-color:#d07468;color:#e6b4ae}.setup-surface footer{display:flex;align-items:center;margin-top:auto;padding-top:13px;border-top:1px solid #233133}.setup-surface footer>span,.setup-surface footer>i{display:none}.tray-button{margin-left:auto;padding:4px 0;font-size:11px}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #43d6d3;outline-offset:2px}
@media (max-width:560px){.setup-surface{padding:19px 19px 14px}.field-grid{grid-template-columns:1fr}.setup-header h1{font-size:20px}}
</style>`;
