export type CirceSemanticEvalSplit = "dev" | "heldout";

export type CirceSemanticEvalCategory =
  | "basic"
  | "destination-vs-mention"
  | "negation-constraint-quote"
  | "multi-span"
  | "correction-asr-alias"
  | "provider"
  | "absent-catalog-pending-compound";

export type CirceSemanticEvalCommand =
  | "start"
  | "continue"
  | "queue"
  | "stop"
  | "status"
  | "review"
  | "reroute"
  | "switch-focus"
  | "answer"
  | "list-projects"
  | "converse";

export type CirceSemanticEvalCase = {
  readonly id: string;
  readonly utterance: string;
  readonly action:
    | "start"
    | "continue"
    | "steer"
    | "queue"
    | "stop"
    | "status"
    | "review"
    | "reroute"
    | "focus-project"
    | "focus-task"
    | "list-projects"
    | "converse"
    | "unsupported";
  readonly task?: string;
  readonly project?: string;
  readonly provider?: string;
  readonly continueContext?: boolean;
  /** Reviewed split: iterate on dev, measure finally on heldout. Heldout is frozen. */
  readonly split: CirceSemanticEvalSplit;
  /** Phenomenon this case guards. */
  readonly category: CirceSemanticEvalCategory;
  /**
   * Substrings that must survive verbatim (normalized) in the proposal
   * instruction and in the interpreted command instruction. Covers negation,
   * constraints, and quoted spans.
   */
  readonly instructionContains?: ReadonlyArray<string>;
  /**
   * Full expected instruction (normalized compare). Stronger than span
   * inclusion: the carried instruction must equal this, not merely contain
   * fragments of it.
   */
  readonly expectedInstruction?: string;
  /** Typed command the Director must produce (or omit, for clarifications). */
  readonly expectedCommand?: CirceSemanticEvalCommand;
  /** True when the deterministic layer must ask for clarification. */
  readonly expectClarification?: boolean;
  /** Needs-input reason required when clarification is expected. */
  readonly expectedClarificationReason?: string;
  /** Per-case Director context beyond the shared catalog fixture. */
  readonly context?: {
    readonly aliases?: ReadonlyArray<{ alias: string; project: string }>;
    readonly voice?: boolean;
    readonly pendingApproval?: boolean;
  };
  /**
   * Representative model proposal replayed by --offline, so grounding and
   * instruction checks run without billing a supervisor call. Cases without
   * one are skipped offline, never scored as passing.
   */
  readonly fixtureIntent?: unknown;
};

const dev = "dev" as const;
const heldout = "heldout" as const;
const basic = "basic" as const;

export const circeSemanticEvalCorpus: ReadonlyArray<CirceSemanticEvalCase> = [
  {
    id: "start-01",
    utterance: "Fix the login redirect in Rivvl.",
    action: "start",
    project: "Rivvl",
    split: dev,
    category: basic,
  },
  {
    id: "start-02",
    utterance: "Add keyboard navigation to the command menu.",
    action: "start",
    split: dev,
    category: basic,
  },
  {
    id: "start-03",
    utterance: "Use Codex to tighten the websocket retry logic.",
    action: "start",
    provider: "Codex",
    split: dev,
    category: basic,
  },
  {
    id: "start-04",
    utterance: "In Beacon, document the three capability presets.",
    action: "start",
    project: "Beacon",
    split: dev,
    category: basic,
  },
  {
    id: "start-05",
    utterance: "Ask Claude to fix the flaky cache test.",
    action: "start",
    provider: "Claude",
    split: dev,
    category: basic,
  },
  {
    id: "start-06",
    utterance: "Create a health check for the VPS worker.",
    action: "start",
    project: "VPS",
    split: dev,
    category: basic,
  },
  {
    id: "start-07",
    utterance: "Refactor the task title formatter without changing behavior.",
    action: "start",
    split: dev,
    category: basic,
  },
  {
    id: "start-08",
    utterance: "Use Codex in Rivvl to add an auth integration test.",
    action: "start",
    project: "Rivvl",
    provider: "Codex",
    split: dev,
    category: basic,
  },
  {
    id: "start-09",
    utterance: "Investigate why mobile reconnects twice.",
    action: "start",
    split: dev,
    category: basic,
  },
  {
    id: "start-10",
    utterance: "Have Claude update the release checklist in Beacon.",
    action: "start",
    project: "Beacon",
    provider: "Claude",
    split: dev,
    category: basic,
  },

  {
    id: "continue-01",
    utterance: "Continue Rivvl authentication and run the integration tests.",
    action: "continue",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "continue-02",
    utterance: "On the release docs task, add the upgrade notes.",
    action: "continue",
    task: "Release docs",
    split: dev,
    category: basic,
  },
  {
    id: "continue-03",
    utterance: "Continue deployment rollout and verify the health endpoint.",
    action: "continue",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "continue-04",
    utterance: "Go back to checkout cleanup and remove the dead branch.",
    action: "continue",
    task: "Checkout cleanup",
    split: dev,
    category: basic,
  },
  {
    id: "continue-05",
    utterance: "Now add an example for remote nodes.",
    action: "continue",
    continueContext: true,
    split: dev,
    category: basic,
  },
  {
    id: "continue-06",
    utterance: "Run the focused tests next.",
    action: "continue",
    continueContext: true,
    split: dev,
    category: basic,
  },
  {
    id: "continue-07",
    utterance: "Keep going and update the user docs.",
    action: "continue",
    continueContext: true,
    split: dev,
    category: basic,
  },

  {
    id: "steer-01",
    utterance: "Tell Rivvl authentication to use SQLite instead.",
    action: "steer",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "steer-02",
    utterance: "For deployment rollout, do not restart the healthy node.",
    action: "steer",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "steer-03",
    utterance: "Change Rivvl authentication to test the token refresh path first.",
    action: "steer",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "steer-04",
    utterance: "Tell deployment rollout to keep the existing tunnel.",
    action: "steer",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "steer-05",
    utterance: "Redirect Rivvl authentication: preserve the old cookie migration.",
    action: "steer",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "steer-06",
    utterance: "While deployment rollout is running, check disk space before continuing.",
    action: "steer",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },

  {
    id: "queue-01",
    utterance: "After Rivvl authentication finishes, update the release notes.",
    action: "queue",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "queue-02",
    utterance: "Queue a smoke test after deployment rollout.",
    action: "queue",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "queue-03",
    utterance: "When checkout cleanup is done, run the linter.",
    action: "queue",
    task: "Checkout cleanup",
    split: dev,
    category: basic,
  },
  {
    id: "queue-04",
    utterance: "After release docs, check every link.",
    action: "queue",
    task: "Release docs",
    split: dev,
    category: basic,
  },
  {
    id: "queue-05",
    utterance: "Add a rollback note after deployment rollout completes.",
    action: "queue",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },

  {
    id: "stop-01",
    utterance: "Stop Rivvl authentication.",
    action: "stop",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "stop-02",
    utterance: "Cancel deployment rollout now.",
    action: "stop",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "stop-03",
    utterance: "Interrupt the checkout cleanup task.",
    action: "stop",
    task: "Checkout cleanup",
    split: dev,
    category: basic,
  },
  {
    id: "stop-04",
    utterance: "Stop release docs and clear its follow-ups.",
    action: "stop",
    task: "Release docs",
    split: dev,
    category: basic,
  },
  {
    id: "stop-05",
    utterance: "Please halt Rivvl authentication.",
    action: "stop",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },

  {
    id: "status-01",
    utterance: "What's the status of Rivvl authentication?",
    action: "status",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "status-02",
    utterance: "Is deployment rollout still running?",
    action: "status",
    task: "Deployment rollout",
    split: dev,
    category: basic,
  },
  {
    id: "status-03",
    utterance: "How did checkout cleanup finish?",
    action: "status",
    task: "Checkout cleanup",
    split: dev,
    category: basic,
  },
  {
    id: "status-04",
    utterance: "Give me the current state of release docs.",
    action: "status",
    task: "Release docs",
    split: dev,
    category: basic,
  },
  {
    id: "status-05",
    utterance: "Report on the Rivvl authentication task.",
    action: "status",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },

  {
    id: "review-01",
    utterance: "Have Claude review Rivvl authentication.",
    action: "review",
    task: "Rivvl authentication",
    provider: "Claude",
    split: dev,
    category: basic,
  },
  {
    id: "review-02",
    utterance: "Use Codex to review the checkout cleanup result.",
    action: "review",
    task: "Checkout cleanup",
    provider: "Codex",
    split: dev,
    category: basic,
  },
  {
    id: "review-03",
    utterance: "Ask Claude for an independent review of release docs.",
    action: "review",
    task: "Release docs",
    provider: "Claude",
    split: dev,
    category: basic,
  },
  {
    id: "review-04",
    utterance: "Review deployment rollout with Codex.",
    action: "review",
    task: "Deployment rollout",
    provider: "Codex",
    split: dev,
    category: basic,
  },

  {
    id: "reroute-01",
    utterance: "Move Rivvl authentication to the VPS project.",
    action: "reroute",
    task: "Rivvl authentication",
    project: "VPS",
    split: dev,
    category: basic,
  },
  {
    id: "reroute-02",
    utterance: "Redo checkout cleanup in Rivvl.",
    action: "reroute",
    task: "Checkout cleanup",
    project: "Rivvl",
    split: dev,
    category: basic,
  },
  {
    id: "reroute-03",
    utterance: "Move deployment rollout into Beacon.",
    action: "reroute",
    task: "Deployment rollout",
    project: "Beacon",
    split: dev,
    category: basic,
  },

  {
    id: "focus-project-01",
    utterance: "Switch to the Rivvl project.",
    action: "focus-project",
    project: "Rivvl",
    split: dev,
    category: basic,
  },
  {
    id: "focus-project-02",
    utterance: "Use VPS for new work.",
    action: "focus-project",
    project: "VPS",
    split: dev,
    category: basic,
  },
  {
    id: "focus-task-01",
    utterance: "Focus the release docs task.",
    action: "focus-task",
    task: "Release docs",
    split: dev,
    category: basic,
  },
  {
    id: "focus-task-02",
    utterance: "Switch to Rivvl authentication.",
    action: "focus-task",
    task: "Rivvl authentication",
    split: dev,
    category: basic,
  },
  {
    id: "list-projects-01",
    utterance: "What projects do I have?",
    action: "list-projects",
    split: dev,
    category: basic,
  },

  // Destination vs mention: the project that receives the work wins, and a
  // merely mentioned project stays in the instruction text.
  {
    id: "dest-01",
    utterance: "In Beacon, fix the login redirect that Rivvl reported.",
    action: "start",
    project: "Beacon",
    split: dev,
    category: "destination-vs-mention",
    instructionContains: ["login redirect", "Rivvl"],
    // Intended dispatch: leading destination stripped, incidental mention kept.
    expectedInstruction: "fix the login redirect that Rivvl reported.",
    expectedCommand: "start",
    context: { aliases: [{ alias: "Jarv", project: "Beacon" }] },
    fixtureIntent: {
      action: "start",
      acknowledgement: "Fixing the login redirect Rivvl reported.",
      project: "Beacon",
      task: null,
      instruction: "In Beacon, fix the login redirect that Rivvl reported.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "dest-02",
    utterance: "For the VPS worker, copy the retry logic Rivvl uses for token refresh.",
    action: "start",
    project: "VPS",
    split: dev,
    category: "destination-vs-mention",
    instructionContains: ["retry logic", "token refresh"],
    expectedInstruction: "For the VPS worker, copy the retry logic Rivvl uses for token refresh.",
    expectedCommand: "start",
    fixtureIntent: {
      action: "start",
      acknowledgement: "Copying the retry logic to the VPS worker.",
      project: "VPS",
      task: null,
      instruction: "For the VPS worker, copy the retry logic Rivvl uses for token refresh.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "dest-03",
    utterance: "Tell deployment rollout to keep the tunnel Rivvl recommended.",
    action: "steer",
    task: "Deployment rollout",
    split: dev,
    category: "destination-vs-mention",
    instructionContains: ["tunnel", "Rivvl"],
    expectedInstruction: "Tell deployment rollout to keep the tunnel Rivvl recommended.",
    expectedCommand: "continue",
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Deployment rollout",
      instruction: "Tell deployment rollout to keep the tunnel Rivvl recommended.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "dest-04",
    utterance: "In Rivvl, document the checkout flow Beacon uses for releases.",
    action: "start",
    project: "Rivvl",
    split: heldout,
    category: "destination-vs-mention",
    instructionContains: ["checkout flow", "Beacon"],
    fixtureIntent: {
      action: "start",
      acknowledgement: "Documenting the checkout flow in Rivvl.",
      project: "Rivvl",
      task: null,
      instruction: "document the checkout flow Beacon uses for releases",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "dest-05",
    utterance: "Move checkout cleanup into VPS, keeping the Beacon history note.",
    action: "reroute",
    task: "Checkout cleanup",
    project: "VPS",
    split: heldout,
    category: "destination-vs-mention",
    fixtureIntent: {
      action: "reroute",
      acknowledgement: "Moving checkout cleanup to VPS.",
      project: "VPS",
      task: "Checkout cleanup",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "dest-06",
    utterance: "While in Beacon, check whether Rivvl authentication is still running.",
    action: "status",
    task: "Rivvl authentication",
    split: heldout,
    category: "destination-vs-mention",
    fixtureIntent: {
      action: "status",
      acknowledgement: null,
      project: null,
      task: "Rivvl authentication",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },

  // Negation, constraints, and quoted spans must survive into the instruction.
  {
    id: "neg-01",
    utterance: 'Tell Rivvl authentication to use the "token refresh" path, not the cookie path.',
    action: "steer",
    task: "Rivvl authentication",
    split: dev,
    category: "negation-constraint-quote",
    instructionContains: ["token refresh", "not the cookie"],
    expectedInstruction:
      'Tell Rivvl authentication to use the "token refresh" path, not the cookie path.',
    expectedCommand: "continue",
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Rivvl authentication",
      instruction:
        'Tell Rivvl authentication to use the "token refresh" path, not the cookie path.',
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "neg-02",
    utterance:
      "For deployment rollout, do not restart the healthy node; only update the drained one.",
    action: "steer",
    task: "Deployment rollout",
    split: dev,
    category: "negation-constraint-quote",
    instructionContains: ["do not restart", "drained"],
    expectedInstruction:
      "For deployment rollout, do not restart the healthy node; only update the drained one.",
    expectedCommand: "continue",
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Deployment rollout",
      instruction:
        "For deployment rollout, do not restart the healthy node; only update the drained one.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "neg-03",
    utterance:
      'In Beacon, document the three capability presets without changing the "Headless" wording.',
    action: "start",
    project: "Beacon",
    split: dev,
    category: "negation-constraint-quote",
    instructionContains: ["capability presets", "Headless"],
    expectedInstruction:
      'In Beacon, document the three capability presets without changing the "Headless" wording.',
    expectedCommand: "start",
    fixtureIntent: {
      action: "start",
      acknowledgement: "Documenting the three capability presets.",
      project: "Beacon",
      task: null,
      instruction:
        'In Beacon, document the three capability presets without changing the "Headless" wording.',
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "neg-04",
    utterance: 'Continue release docs but keep the "upgrade notes" section exactly as written.',
    action: "continue",
    task: "Release docs",
    split: heldout,
    category: "negation-constraint-quote",
    instructionContains: ["upgrade notes", "exactly"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Adding to the release docs.",
      project: null,
      task: "Release docs",
      instruction: 'keep the "upgrade notes" section exactly as written and continue the docs',
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "neg-05",
    utterance: "Queue a smoke test after deployment rollout, excluding the billing endpoint.",
    action: "queue",
    task: "Deployment rollout",
    split: heldout,
    category: "negation-constraint-quote",
    instructionContains: ["smoke test", "billing"],
    fixtureIntent: {
      action: "queue",
      acknowledgement: null,
      project: null,
      task: "Deployment rollout",
      instruction: "run a smoke test excluding the billing endpoint",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "neg-06",
    utterance:
      'Tell checkout cleanup to pause the branch deletes, but do not delete the "dead branch" list.',
    action: "steer",
    task: "Checkout cleanup",
    split: heldout,
    category: "negation-constraint-quote",
    instructionContains: ["dead branch"],
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Checkout cleanup",
      instruction: 'pause the branch deletes, but do not delete the "dead branch" list',
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },

  // Multi-span requests: compounds propose unsupported and never dispatch
  // a lead fragment. The host answers needs-input instead.
  {
    id: "multi-01",
    utterance: "After Rivvl authentication finishes, update the release notes and tell me.",
    action: "unsupported",
    split: dev,
    category: "multi-span",
    expectedInstruction:
      "After Rivvl authentication finishes, update the release notes and tell me.",
    expectClarification: true,
    expectedClarificationReason: "unsupported-command",
    fixtureIntent: {
      action: "unsupported",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "After Rivvl authentication finishes, update the release notes and tell me.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "multi-02",
    utterance:
      "Compare Rivvl authentication with checkout cleanup, then continue the auth work with the token test.",
    action: "unsupported",
    split: dev,
    category: "multi-span",
    expectedInstruction:
      "Compare Rivvl authentication with checkout cleanup, then continue the auth work with the token test.",
    expectClarification: true,
    expectedClarificationReason: "unsupported-command",
    fixtureIntent: {
      action: "unsupported",
      acknowledgement: null,
      project: null,
      task: null,
      instruction:
        "Compare Rivvl authentication with checkout cleanup, then continue the auth work with the token test.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "multi-03",
    utterance: "Stop deployment rollout, snapshot the logs, and queue a retry note.",
    action: "unsupported",
    split: dev,
    category: "multi-span",
    expectedInstruction: "Stop deployment rollout, snapshot the logs, and queue a retry note.",
    expectClarification: true,
    expectedClarificationReason: "unsupported-command",
    fixtureIntent: {
      action: "unsupported",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "Stop deployment rollout, snapshot the logs, and queue a retry note.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "multi-04",
    utterance:
      "While deployment rollout runs, check disk space and steer it to skip the healthy node.",
    action: "steer",
    task: "Deployment rollout",
    split: heldout,
    category: "multi-span",
    instructionContains: ["disk space", "healthy"],
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Deployment rollout",
      instruction: "check disk space and skip the healthy node",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "multi-05",
    utterance: "Review Rivvl authentication with Claude and post the findings to release docs.",
    action: "review",
    task: "Rivvl authentication",
    provider: "Claude",
    split: heldout,
    category: "multi-span",
    instructionContains: ["findings", "release docs"],
    fixtureIntent: {
      action: "review",
      acknowledgement: "Reviewing the auth result.",
      project: null,
      task: "Rivvl authentication",
      instruction: "review Rivvl authentication and post the findings to release docs",
      provider: "Claude",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "multi-06",
    utterance: "When release docs is done, check every link and report back.",
    action: "queue",
    task: "Release docs",
    split: heldout,
    category: "multi-span",
    instructionContains: ["link"],
    fixtureIntent: {
      action: "queue",
      acknowledgement: null,
      project: null,
      task: "Release docs",
      instruction: "check every link and report back",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },

  // Corrections, ASR slips, and aliases: the model normalizes to catalog names.
  {
    id: "asr-01",
    utterance: "Continue Rival authentication and run the integration tests.",
    action: "continue",
    task: "Rivvl authentication",
    split: dev,
    category: "correction-asr-alias",
    instructionContains: ["integration tests"],
    expectedInstruction: "Continue Rival authentication and run the integration tests.",
    expectedCommand: "continue",
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Continuing the auth work.",
      project: null,
      task: "Rivvl authentication",
      instruction: "Continue Rival authentication and run the integration tests.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-02",
    utterance: "No, I meant the VPS deployment, not Rivvl: verify the health endpoint.",
    action: "continue",
    task: "Deployment rollout",
    split: dev,
    category: "correction-asr-alias",
    instructionContains: ["health endpoint"],
    expectedInstruction: "No, I meant the VPS deployment, not Rivvl: verify the health endpoint.",
    expectedCommand: "continue",
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Checking the VPS deployment.",
      project: null,
      task: "Deployment rollout",
      instruction: "No, I meant the VPS deployment, not Rivvl: verify the health endpoint.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-03",
    utterance: "Switch to the Rivvil project.",
    action: "focus-project",
    project: "Rivvl",
    split: dev,
    category: "correction-asr-alias",
    // The typo never speaks "Rivvl", so the mention gate must ask even
    // though the model normalized to the catalog name.
    expectClarification: true,
    expectedClarificationReason: "control-target-required",
    fixtureIntent: {
      action: "focus-project",
      acknowledgement: null,
      project: "Rivvl",
      task: null,
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-04",
    utterance: "Tell Rivvl auth to test the token refresh first.",
    action: "steer",
    task: "Rivvl authentication",
    split: dev,
    category: "correction-asr-alias",
    instructionContains: ["token refresh"],
    expectedInstruction: "Tell Rivvl auth to test the token refresh first.",
    expectedCommand: "continue",
    fixtureIntent: {
      action: "steer",
      acknowledgement: null,
      project: null,
      task: "Rivvl authentication",
      instruction: "Tell Rivvl auth to test the token refresh first.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-05",
    utterance: "Continue rebel authentication and rerun the token test.",
    action: "continue",
    task: "Rivvl authentication",
    split: heldout,
    category: "correction-asr-alias",
    instructionContains: ["token"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Continuing the auth work.",
      project: null,
      task: "Rivvl authentication",
      instruction: "rerun the token test",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-06",
    utterance: "Go back to checkout clean up and remove the dead branch.",
    action: "continue",
    task: "Checkout cleanup",
    split: heldout,
    category: "correction-asr-alias",
    instructionContains: ["dead branch"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Picking up checkout cleanup.",
      project: null,
      task: "Checkout cleanup",
      instruction: "remove the dead branch",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-07",
    utterance: "Focus the Rivvl authentification task.",
    action: "focus-task",
    task: "Rivvl authentication",
    split: heldout,
    category: "correction-asr-alias",
    fixtureIntent: {
      action: "focus-task",
      acknowledgement: null,
      project: null,
      task: "Rivvl authentication",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "asr-08",
    utterance: "Sorry, the release doc task: add the upgrade notes.",
    action: "continue",
    task: "Release docs",
    split: heldout,
    category: "correction-asr-alias",
    instructionContains: ["upgrade notes"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Adding to the release docs.",
      project: null,
      task: "Release docs",
      instruction: "add the upgrade notes",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },

  // Provider routing: named provider wins, others stay mentions.
  {
    id: "prov-01",
    utterance: "Use Codex to review the checkout cleanup result and keep the notes short.",
    action: "review",
    task: "Checkout cleanup",
    provider: "Codex",
    split: dev,
    category: "provider",
    expectedInstruction:
      "Use Codex to review the checkout cleanup result and keep the notes short.",
    expectedCommand: "review",
    fixtureIntent: {
      action: "review",
      acknowledgement: "Reviewing the checkout result.",
      project: null,
      task: "Checkout cleanup",
      instruction: "Use Codex to review the checkout cleanup result and keep the notes short.",
      provider: "Codex",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "prov-02",
    utterance: "Ask Claude to fix the flaky cache test in Rivvl.",
    action: "start",
    project: "Rivvl",
    provider: "Claude",
    split: dev,
    category: "provider",
    expectedInstruction: "Ask Claude to fix the flaky cache test in Rivvl.",
    expectedCommand: "start",
    fixtureIntent: {
      action: "start",
      acknowledgement: "Fixing the flaky cache test.",
      project: "Rivvl",
      task: null,
      instruction: "Ask Claude to fix the flaky cache test in Rivvl.",
      provider: "Claude",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "prov-03",
    utterance: "In VPS, have Codex add an auth integration test, not the load test.",
    action: "start",
    project: "VPS",
    provider: "Codex",
    split: dev,
    category: "provider",
    instructionContains: ["integration test", "not the load test"],
    // Intended dispatch: leading destination stripped, constraint kept.
    expectedInstruction: "have Codex add an auth integration test, not the load test.",
    expectedCommand: "start",
    fixtureIntent: {
      action: "start",
      acknowledgement: "Adding the auth integration test.",
      project: "VPS",
      task: null,
      instruction: "In VPS, have Codex add an auth integration test, not the load test.",
      provider: "Codex",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "prov-04",
    utterance: "Have Claude review the deployment rollout result.",
    action: "review",
    task: "Deployment rollout",
    provider: "Claude",
    split: heldout,
    category: "provider",
    fixtureIntent: {
      action: "review",
      acknowledgement: "Reviewing the rollout result.",
      project: null,
      task: "Deployment rollout",
      instruction: "review the deployment rollout result",
      provider: "Claude",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "prov-05",
    utterance: "With Codex, continue Rivvl authentication using the token refresh test.",
    action: "continue",
    task: "Rivvl authentication",
    provider: "Codex",
    split: heldout,
    category: "provider",
    instructionContains: ["token refresh"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Continuing the auth work.",
      project: null,
      task: "Rivvl authentication",
      instruction: "continue using the token refresh test",
      provider: "Codex",
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "prov-06",
    utterance: "Start a VPS health check with Claude, keeping the existing alerts.",
    action: "start",
    project: "VPS",
    provider: "Claude",
    split: heldout,
    category: "provider",
    instructionContains: ["health check", "alerts"],
    fixtureIntent: {
      action: "start",
      acknowledgement: "Starting the VPS health check.",
      project: "VPS",
      task: null,
      instruction: "start a VPS health check, keeping the existing alerts",
      provider: "Claude",
      model: null,
      effort: null,
      answer: null,
    },
  },

  // Absent catalogs, pending compounds, and general questions.
  {
    id: "absent-01",
    utterance: "Move checkout cleanup to the Mobile project.",
    action: "reroute",
    task: "Checkout cleanup",
    project: "Mobile",
    split: dev,
    category: "absent-catalog-pending-compound",
    expectClarification: true,
    expectedClarificationReason: "control-target-required",
    fixtureIntent: {
      action: "reroute",
      acknowledgement: "Moving checkout cleanup to Mobile.",
      project: "Mobile",
      task: "Checkout cleanup",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-02",
    utterance: "What's the status of the billing migration?",
    action: "status",
    task: "billing migration",
    split: dev,
    category: "absent-catalog-pending-compound",
    expectClarification: true,
    expectedClarificationReason: "control-target-required",
    fixtureIntent: {
      action: "status",
      acknowledgement: null,
      project: null,
      task: "billing migration",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-03",
    utterance:
      "After the approval lands, continue Rivvl authentication with the token refresh test.",
    action: "continue",
    task: "Rivvl authentication",
    split: dev,
    category: "absent-catalog-pending-compound",
    instructionContains: ["approval", "token refresh"],
    expectedInstruction:
      "After the approval lands, continue Rivvl authentication with the token refresh test.",
    expectedCommand: "continue",
    context: { pendingApproval: true },
    fixtureIntent: {
      action: "continue",
      acknowledgement: "Continuing the auth work.",
      project: null,
      task: "Rivvl authentication",
      instruction:
        "After the approval lands, continue Rivvl authentication with the token refresh test.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-04",
    utterance: "What projects do I have for billing?",
    action: "list-projects",
    split: dev,
    category: "absent-catalog-pending-compound",
    expectedCommand: "list-projects",
    fixtureIntent: {
      action: "list-projects",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-05",
    utterance: "Stop the billing migration task now.",
    action: "stop",
    task: "billing migration",
    split: heldout,
    category: "absent-catalog-pending-compound",
    expectClarification: true,
    fixtureIntent: {
      action: "stop",
      acknowledgement: null,
      project: null,
      task: "billing migration",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-06",
    utterance: "Is that a good architecture?",
    action: "continue",
    split: heldout,
    category: "absent-catalog-pending-compound",
    instructionContains: ["architecture"],
    fixtureIntent: {
      action: "continue",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "is that a good architecture?",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "absent-07",
    utterance: "What is new today?",
    action: "converse",
    split: heldout,
    category: "absent-catalog-pending-compound",
    instructionContains: ["new today"],
    fixtureIntent: {
      action: "converse",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "what is new today?",
      provider: null,
      model: null,
      effort: null,
      answer: "Nothing new: no provider runs are active.",
    },
  },
  {
    id: "absent-08",
    utterance: "Explain the difference between steer and queue.",
    action: "converse",
    split: heldout,
    category: "absent-catalog-pending-compound",
    instructionContains: ["steer", "queue"],
    fixtureIntent: {
      action: "converse",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "explain the difference between steer and queue",
      provider: null,
      model: null,
      effort: null,
      answer: "Steer adds direction to running work. Queue schedules a follow-up.",
    },
  },

  // A negated destructive control resolves to the positive action named, and
  // a bare approval verdict answers the pending request as typed.
  {
    id: "neg-07",
    utterance: "Don't stop Rivvl authentication, just tell me its status.",
    action: "status",
    task: "Rivvl authentication",
    split: dev,
    category: "negation-constraint-quote",
    expectedCommand: "status",
    fixtureIntent: {
      action: "status",
      acknowledgement: null,
      project: null,
      task: "Rivvl authentication",
      instruction: null,
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
  {
    id: "pending-01",
    utterance: "Yes, allow it.",
    action: "continue",
    split: dev,
    category: "absent-catalog-pending-compound",
    expectedInstruction: "Yes, allow it.",
    expectedCommand: "answer",
    continueContext: true,
    context: { pendingApproval: true },
    fixtureIntent: {
      action: "continue",
      acknowledgement: null,
      project: null,
      task: null,
      instruction: "Yes, allow it.",
      provider: null,
      model: null,
      effort: null,
      answer: null,
    },
  },
];
